import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Cetha - Upgrade CV, Upgrade Karir",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico',
    apple: '/apple-touch-icon.png'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased"
      >
        {children}
      </body>
    </html>
  );
}
